import { CapitalInfo } from '../dto/capital-info';
import { Car } from '../dto/car';
import { CoatOfArms } from '../dto/coat-of-arms';
import { Currencies } from '../dto/currencies';
import { Demonyms } from '../dto/demonyms';
import { Flags } from '../dto/flags';
import { Gini } from '../dto/gini';
import { Idd } from '../dto/idd';
import { Languages } from '../dto/languages';
import { Maps } from '../dto/maps';
import { Name } from '../dto/name';
import { Translation } from '../dto/translation';
import { PostalCode } from '../dto/postal-code';

export interface Country {
  name:        Name;
  tld:         string[];
  cca2:        string;
  ccn3:         string;
  cca3:         string;
  cioc:         string;
  independent:  boolean;
  status:       string;
  unMember:     boolean;
  currencies:   Currencies;
  idd:          Idd;
  capital:      string[];
  altSpellings: string[];
  region:       string;
  subregion:    string;
  languages:    Languages;
  translations: { [key: string]: Translation };
  latlng:       number[];
  landlocked:   boolean;
  borders:      string[];
  area:         number;
  demonyms:     Demonyms;
  flag:         string;
  maps:         Maps;
  population:   number;
  gini:         Gini;
  fifa:         string;
  car:          Car;
  timezones:    string[];
  continents:   string[];
  flags:        Flags;
  coatOfArms:   CoatOfArms;
  startOfWeek:  string;
  capitalInfo:  CapitalInfo;
  postalCode:   PostalCode;
}
